const mockDB = [
  {
    carName: "Vuxhall Grandland X",
    carImage: "/images/car1.png",
    carSubname: "1.2L SE Turbo",
    miles: 36815,
    reg: 2019,
    trans: "Manual",
    fuel: "Petrol",
    price: 14000,
  },
  {
    carName: "Kia Sportage",
    carImage: "/images/car2.png",
    carSubname: "1.6L 2 GDi",
    miles: 48907,
    reg: 2019,
    trans: "Manual",
    fuel: "Petrol",
    price: 15750,
  },
  {
    carName: "BMW 2 Series Gran Coupe",
    carImage: "/images/car3.png",
    carSubname: "1.5L M Sport 218i",
    miles: 10820,
    reg: 2021,
    trans: "Automatic",
    fuel: "Petrol",
    price: 14000,
  },
  {
    carName: "Fiat Panda",
    carImage: "/images/car4.png",
    carSubname: "1.2L Popi",
    miles: 16688,
    reg: 2016,
    trans: "Manual",
    fuel: "Petrol",
    price: 6650,
  },
  {
    carName: "Vauxhall Corsa",
    carImage: "/images/car5.png",
    carSubname: "1.4L Design ecoFLEX i",
    miles: 56286,
    reg: 2017,
    trans: "Manual",
    fuel: "Petrol",
    price: 7050,
  },
  {
    carName: "MG MG3",
    carImage: "/images/car6.png",
    carSubname: "1.5L 3Form Sport VTi-TECH",
    miles: 42916,
    reg: 2015,
    trans: "Manual",
    fuel: "Petrol",
    price: 5550,
  },
  {
    carName: "Suzuki Celerio",
    carImage: "/images/car7.png",
    carSubname: "1L SZ2",
    miles: 11166,
    reg: 2017,
    trans: "Manual",
    fuel: "Petrol",
    price: 7100,
  },
  {
    carName: "Dacia Sandero",
    carImage: "/images/car8.png",
    carSubname: "1L Essential SCe",
    miles: 20414,
    reg: 2018,
    trans: "Manual",
    fuel: "Petrol",
    price: 7000,
  },
  {
    carName: "Toyota AYGO",
    carImage: "/images/car9.png",
    carSubname: "1L x-press VVT-i",
    miles: 50335,
    reg: 2017,
    trans: "Manual",
    fuel: "Petrol",
    price: 7550,
  },
];

export default mockDB;
